Podfile, Podfile.lock, maki-maki-ios/Registration/SignUpViewController.swift
link to epic: https://startmobile.atlassian.net/browse/MAKI-1?atlOrigin=eyJpIjoiMWZlYjA1YWFjNDhlNDIxNDlmZmJlNTEwYjkzMjlhMzgiLCJwIjoiaiJ9
=> [MAKI-32] - Добавить для TextField label

maki-maki-ios.xcodeproj/project.pbxproj, maki-maki-ios/Orders/NoOrdersView.swift, maki-maki-ios/Orders/OrdersViewController.swift
Ссылка на задачу: 
https://startmobile.atlassian.net/browse/MAKI-69
Добавил noOrdersView  по поинтам в фигме. Была мысль по центру прикрепить, но пока решил по фигме.
=> [MAKI-69] Добавить логику показа экрана пустого заказа.

maki-maki-ios/Orders/NoOrdersView.swift, maki-maki-ios/Orders/OrdersViewController.swift
Ccылка на задачу:
https://startmobile.atlassian.net/browse/MAKI-86
Шыңғыс подсказал лучше способ реализовать эту логику черещ tableView.backgrounView. Так и сделал.
=> [MAKI-86] - Поменять способ показа NoOrdersView.

maki-maki-ios/Orders/OrdersTableFooterView.swift, maki-maki-ios/Orders/OrdersViewController.swift
Реализован переход на корзину при нажатии кнопки Reorder в Orders.
https://startmobile.atlassian.net/browse/MAKI-78
=> [MAKI-78] Сделать delegate для корзины

Podfile, Podfile.lock, maki-maki-ios.xcodeproj/project.pbxproj, maki-maki-ios/Registration/WelcomePageVerOneViewController.swift, maki-maki-ios/SnackBarApp/SnackBarController.swift
**SnackBar**(Телефон) и поправка кода.
**Jira**: https://startmobile.atlassian.net/browse/MAKI-109?atlOrigin=eyJpIjoiOWYyYWRkMTkyYzU0NDFjMmFlMTQ3ZmZkNzY4NWJlMTgiLCJwIjoiaiJ9
- Реализован **SnackBar** для ошибок. 
- Был  поправлен код с удалением символ для телефона.
- Добавил pod '**SnackBar.swift**'.
- Сделал адаптивный и понятный код.
=> [MAKI-109] - SnackBar(Телефон) и поправки кода

maki-maki-ios/Dish/DishViewController.swift
https://startmobile.atlassian.net/browse/MAKI-99
=> [MAKI-99] NEW - Логика выбранных продуктов

maki-maki-ios/RestaurantMenu/Category Menu/CategoryMenuView.swift, maki-maki-ios/RestaurantMenu/RestaurantViewController.swift
Ссылка на задачу: 
https://startmobile.atlassian.net/jira/software/c/projects/MAKI/boards/1?modal=detail&selectedIssue=MAKI-112&assignee=712020%3A37269cd5-3e03-44cd-865a-788df4cfec31
Было: 
https://github.com/startmobile-kz/makimaki.kz/assets/75442373/90a66f5a-a443-4096-9b43-8abb1046121f
Пофиксил эту проблему и другие недочеты. 
Стало: 
https://github.com/startmobile-kz/makimaki.kz/assets/75442373/74bb1a87-9a07-4aa2-9b85-728750b2c1fa
=> [MAKI-112] Исправить баг при нажатии на категорию.

Podfile, Podfile.lock
Добавил версии библиотек в Podfile.
Были проблемы при назначении версии SnackBar.swift - указал версию 0.1.0
https://github.com/ahmedAlmasri/SnackBar.swift
Скрин указанных версий:
https://startmobile.atlassian.net/browse/MAKI-123
=> [MAKI-123] Добавить версии библиотек в Podfile

maki-maki-ios/Dish/DishViewController.swift, maki-maki-ios/Dish/StepperView.swift
Восстановление логики выбранных продуктов
=> [MAKI-99] - Логика выбранных продуктов (repair)

maki-maki-ios.xcodeproj/project.pbxproj, maki-maki-ios/Search/Model/SearchHistory.swift, maki-maki-ios/Search/RecentSearchesTableViewCell.swift, maki-maki-ios/Search/SearchV1ViewController.swift, maki-maki-ios/Search/Views/SearchContainerView.swift
https://github.com/startmobile-kz/makimaki.kz/assets/34274122/9cd0d807-201a-43bd-bcdd-c133be255dc5
=> [MAKI-117]: Реализовать логику истории поиска

maki-maki-ios/Orders/OrdersViewController.swift, maki-maki-ios/SceneDelegate.swift
Доработка логики удаления ячейки ReorderCell
=> [MAKI-122] Скрыть footerview в историях

maki-maki-ios/RestaurantMenu/RestaurantViewController.swift, maki-maki-ios/RestaurantMenu/ViewCart/ViewCartContainer.swift
link: https://startmobile.atlassian.net/browse/MAKI-116?atlOrigin=eyJpIjoiMTMwY2Y1NmU1YzU0NGFkZDlkZTJkMjJlMmNlYTJkYjMiLCJwIjoiaiJ9
=> [MAKI-116]-Логика подсчета итоговый суммы 

maki-maki-ios/Dish/DishViewController.swift, maki-maki-ios/Dish/StepperView.swift, maki-maki-ios/SceneDelegate.swift
Поправлены два бага:
-корректное отображение количества продукта при входе на страницу
-корректное отображение суммированной цены при повторном выборе продукта из списка продуктов
Работа проделана совместно с @damiraliyev
https://startmobile.atlassian.net/browse/MAKI-121
=> [MAKI-121] - Баг со степпером

maki-maki-ios.xcodeproj/project.pbxproj
Удалил Kingfisher library из SPM. 
Удаление произошло безболезненно для проекта.
https://startmobile.atlassian.net/browse/MAKI-135
=> [MAKI-135] - Удалить Kingfisher library из SPM

maki-maki-ios/Registration/WelcomePageVerOneViewController.swift
Проверка на **полный номер телефона**.
**Jira**: https://startmobile.atlassian.net/jira/software/c/projects/MAKI/boards/1?modal=detail&selectedIssue=MAKI-138&assignee=5e9306923a8b910c083c6fcd
- Добавил условие на проверку полного номера телефона. 
- Сделал адаптивный и понятный код.
=> [MAKI-138] Проверка на полный номер телефона

maki-maki-ios.xcodeproj/project.pbxproj, maki-maki-ios/NewMainPage/CategoriesViewHeader.swift, maki-maki-ios/NewMainPage/NewMainPageSectionTypes.swift, maki-maki-ios/NewMainPage/SecondMainViewController.swift, maki-maki-ios/NewMainPage/СategoriesHeaderView.swift, maki-maki-ios/SceneDelegate.swift, maki-maki-ios/Tabbar/Main2TabBarController.swift
Ссылка на задачу: https://startmobile.atlassian.net/jira/software/c/projects/MAKI/boards/1?modal=detail&selectedIssue=MAKI-132&assignee=712020%3A37269cd5-3e03-44cd-865a-788df4cfec31
=> [MAKI-132 Сделать верстку новой главной страницы.]

maki-maki-ios.xcodeproj/project.pbxproj, maki-maki-ios/AccountList/AccountListController.swift, maki-maki-ios/EditProfile/EditProfileViewController.swift, maki-maki-ios/EditProfile/User.swift
Обновить **профиль** пользователя после ввода данных
**Jira**: https://startmobile.atlassian.net/jira/software/c/projects/MAKI/boards/1?modal=detail&selectedIssue=MAKI-140&assignee=5e9306923a8b910c083c6fcd
- Добавил делегат и сделал взаимосвязь между EditProfileViewController и AccountListController. 
- Сделал адаптивный и понятный код.
=> [MAKI-140] Обновить профиль пользователя после ввода данных

maki-maki-ios.xcodeproj/project.pbxproj, maki-maki-ios/Registration/Model/Person.swift, maki-maki-ios/Registration/Model/WelcomePageService.swift, maki-maki-ios/Registration/WelcomePageVerOneViewController.swift, maki-maki-ios/SceneDelegate.swift
Переписал запрос в WelcomePageVerOneViewController на Alamofire
Требуется проверка и обратная связь! Статус - задача еще в работе.
ссылка на таск:
https://startmobile.atlassian.net/browse/MAKI-136
=> [MAKI-136][Network] переписать запрос на AF в модуле регистрации

maki-maki-ios/NewMainPage/SecondMainViewController.swift, maki-maki-ios/RestaurantMenu/ViewCart/ViewCartContainer.swift
Ссылка на задачу: https://startmobile.atlassian.net/browse/MAKI-150
=> [MAKI-150] Показ корзины только после выбора продукта.

maki-maki-ios/Dish/DishViewController.swift
Добавлена первоначальная версия сердечка на детальную страницу.
https://startmobile.atlassian.net/browse/MAKI-145
=> [MAKI-145] Добавить сердешка детальная страница еды

maki-maki-ios/Basket/BasketViewController.swift, maki-maki-ios/Basket/ContainerViewController.swift, maki-maki-ios/Basket/Model/Basket.swift, maki-maki-ios/Basket/Model/BasketService.swift
Добавил опцию удаления и корректное отображение всей суммы заказа
=> [MAKI-128]

maki-maki-ios/Helpers/Resourses/AppImage.swift, maki-maki-ios/MainPage/View/DeliveryHeaderView.swift, maki-maki-ios/MainPage/View/PromoBannerCollectionViewCell.swift, maki-maki-ios/NewMainPage/SecondMainViewController.swift, maki-maki-ios/RestaurantMenu/CategoryMenu/CategoryMenuView.swift, maki-maki-ios/RestaurantMenu/ProductMenu/ProductSectionHeaderView.swift
Ссылка на задачу: https://startmobile.atlassian.net/browse/MAKI-149
=> [MAKI-149] Добавить скелетоны в новую главную страницу.
